/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExRupeesRouteImport } from './routes/ex-rupees'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MoiAppRouteImport } from './routes/moi-app'
import { Route as MoiAtComputerRouteImport } from './routes/moi-at-computer'
import { Route as MoiAtHandRouteImport } from './routes/moi-at-hand'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExRupeesRoute = ExRupeesRouteImport.update({
  id: '/ex-rupees',
  path: '/ex-rupees',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiAppRoute = MoiAppRouteImport.update({
  id: '/moi-app',
  path: '/moi-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiAtComputerRoute = MoiAtComputerRouteImport.update({
  id: '/moi-at-computer',
  path: '/moi-at-computer',
  getParentRoute: () => rootRouteImport,
} as any)
const MoiAtHandRoute = MoiAtHandRouteImport.update({
  id: '/moi-at-hand',
  path: '/moi-at-hand',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationsRoute,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => LocationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/ex-rupees': typeof ExRupeesRoute
  '/locations': typeof LocationsRouteWithChildren
  '/moi-app': typeof MoiAppRoute
  '/moi-at-computer': typeof MoiAtComputerRoute
  '/moi-at-hand': typeof MoiAtHandRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/ex-rupees': typeof ExRupeesRoute
  '/moi-app': typeof MoiAppRoute
  '/moi-at-computer': typeof MoiAtComputerRoute
  '/moi-at-hand': typeof MoiAtHandRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/contact': typeof ContactRoute
  '/ex-rupees': typeof ExRupeesRoute
  '/locations': typeof LocationsRouteWithChildren
  '/moi-app': typeof MoiAppRoute
  '/moi-at-computer': typeof MoiAtComputerRoute
  '/moi-at-hand': typeof MoiAtHandRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/locations/$city': typeof LocationsCityRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account-deletion'
    | '/contact'
    | '/ex-rupees'
    | '/locations'
    | '/moi-app'
    | '/moi-at-computer'
    | '/moi-at-hand'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/locations/$city'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account-deletion'
    | '/contact'
    | '/ex-rupees'
    | '/moi-app'
    | '/moi-at-computer'
    | '/moi-at-hand'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/locations/$city'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account-deletion'
    | '/contact'
    | '/ex-rupees'
    | '/locations'
    | '/moi-app'
    | '/moi-at-computer'
    | '/moi-at-hand'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/locations/$city'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  ContactRoute: typeof ContactRoute
  ExRupeesRoute: typeof ExRupeesRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  MoiAppRoute: typeof MoiAppRoute
  MoiAtComputerRoute: typeof MoiAtComputerRoute
  MoiAtHandRoute: typeof MoiAtHandRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex-rupees': {
      id: '/ex-rupees'
      path: '/ex-rupees'
      fullPath: '/ex-rupees'
      preLoaderRoute: typeof ExRupeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-app': {
      id: '/moi-app'
      path: '/moi-app'
      fullPath: '/moi-app'
      preLoaderRoute: typeof MoiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-at-computer': {
      id: '/moi-at-computer'
      path: '/moi-at-computer'
      fullPath: '/moi-at-computer'
      preLoaderRoute: typeof MoiAtComputerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moi-at-hand': {
      id: '/moi-at-hand'
      path: '/moi-at-hand'
      fullPath: '/moi-at-hand'
      preLoaderRoute: typeof MoiAtHandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof LocationsRoute
    }
  }
}

interface LocationsRouteChildren {
  LocationsCityRoute: typeof LocationsCityRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsCityRoute: LocationsCityRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  ContactRoute: ContactRoute,
  ExRupeesRoute: ExRupeesRoute,
  LocationsRoute: LocationsRouteWithChildren,
  MoiAppRoute: MoiAppRoute,
  MoiAtComputerRoute: MoiAtComputerRoute,
  MoiAtHandRoute: MoiAtHandRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
